site_name: MYMY Archive
# site_url: http://127.0.0.1:8000/

theme:
  # name: readthedocs
  name: material
  language: ko
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path

plugins: []

# mermaid support
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
  alternate:
    # - name: English
    #   link: /en/ 
    #   lang: en
    # - name: Korean
    #   link: /
    #   lang: ko
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

nav:
  - 'index.md'
  - '사용자 매뉴얼':
    - '랜딩 페이지': 
      - '랜딩 페이지': 'landing_page/landing_page.md'
      - '회원 가입': 'landing_page/sign_up.md'
      - '로그인': 'landing_page/login_page.md'
      - '아카이브 홈': 'landing_page/archive_home.md'
    - '사용자 설정':
      - '사용자 정보' : 'user_setting/user_info.md'
      - '비밀번호 변경': 'user_setting/change_password.md'
      - '업로드 관리': 'user_setting/upload_management.md'
      - '다운로드 관리': 'user_setting/download_management.md'
    - '아카이브':
      - '카테고리 뷰': 'archive/category_view.md'
      - '애뉴얼 뷰': 'archive/annual_view.md'
    - '검색':
      - '통합검색': 'search/integrated_search.md'
      - '필터': 'search/filter_options.md'
    - '커뮤니티':
      - '커뮤니티 홈': 'community/community_home.md'
      - '커뮤니티 설정': 'community/community_settings.md'
  - '관리자 매뉴얼':
    - '대시보드': 'admin_guide/dashboard.md'
    - '시스템': 'admin_guide/system_settings.md'
    - '스토리지': 'admin_guide/storage_settings.md'
    - '사용자': 'admin_guide/user_management.md'
    - '콘텐츠': 'admin_guide/content_management.md'
    - '아카이브': 'admin_guide/archive_management.md'
    - '메타데이터': 'admin_guide/metadata_management.md'    
    - '커뮤니티 관리': 'admin_guide/community_management.md'
    - '알람': 'admin_guide/alarm_management.md'
  - '오류 해결': 'troubleshooting/troubleshooting.md'
  - 'About': 'about.md'
